apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qq0g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qq0g
    app.kubernetes.io/part-of: integ-app-etil
  name: hacbs-test-project-qq0g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qq0g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qq0g
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-pbks-tenant/integ-app-etil/hacbs-test-project-qq0g@sha256:1063a52a5ab3561e3f46ee61feb038a6bf757c3bb81442f89f48dc8b43562d80
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
